### ISSUE TITLE
deconvolution_nmf zeroes

### ISSUE THREAD

**Issue by ekfchan** [FunGeST/Palimpsest#13]
Hi, 

Can I assume you had included the following two lines of code in the `deconvolution_nmf` function because you want to ensure there are no rows in `input_data` that are all zeroes? 
``` 
sumRows <- rowSums(input_data);sort(sumRows);zeroes <- which(sumRows==0)
if(length(zeroes)){input_data[zeroes,1] <- 1e-10}
```

If that is the case, I don't think it's resulting in the desired effect. By sorting `sumRows` prior to calling `which`, I don't think `zeroes` actually indexes the row(s) you want to manipulate in `input_data`...?

**Comment by jayendrashinde91** [comment]
Hi,
You are absolutely correct. Those couple of lines introduce non-zero values in case of row/s with all zero values. The code does not sort sumRows.
If this answers your question, kindly make sure to close the issue.
Thanks,

Jay

**Comment by ekfchan** [comment]
You're right!  The code does not reassign the sort. Thanks.
