### ISSUE TITLE
bugfix - palimpsest_plotTumorHistories

### ISSUE THREAD

**Issue by sbamin** [FunGeST/Palimpsest#15]
HI Jayendra

Thanks for sharing this code. It has been of much value in timing analysis. I work on canine data and so I'd to edit multiple changes but it is working for most parts except RCircos sv plots. While refactoring code for canine, I found that following lines may need a fix. 

Line 676: Should read `if(length(pq) != 0)` (canine cytoband has all q arms given all chrs are acrocentric with no annotations for a tiny p arm)

Line 678: Should be following as object to `sub` is missing for now. This may not error as hg19 is hardcoded for most part but for other genomes, it will when `length(pq)` > 1.

```r
dels <- dels[order(as.numeric(gsub("p|q","",(sub("X",23, dels), sub("Y",24, dels)))))] 
```

https://github.com/FunGeST/Palimpsest/blob/45775d9aa100bf8bd5bbfb41a238971f13f65299/R/palimpsest_plotting.R#L676-L679

A request: If you can summarize changes you make to package during commit, it would help a lot for me to merge upstream changes. We will share canine fork once manuscript is under review.

**Comment by jayendrashinde91** [comment]
Thanks, Samir. We are glad that the package has been of help to your analysis.
I will definitely go ahead and push your suggested changes soon.
