### ISSUE TITLE
Timing Chromosomal Gains

### ISSUE THREAD

**Issue by xtmgah** [FunGeST/Palimpsest#18]
Hello, I have an question about the understanding of "Timing Chromosomal Gains". So, after chrTime_annot, the vcf will have an column called "Timing" to each mutation. Can you explain what's this timing means and how do you determine the timing for mutations. I found most case there are NA in this column if no copy number gain in the position. Is this prediction corresponded to clonality, for example, "late" means sublcone and "early" means "clonal"? thanks.

**Comment by FunGeST** [comment]
Hi xtmgah,
The timing of chromosome duplications are based on the proportions of duplicated/non-duplicated somatic mutations, as explained here: https://www.nature.com/articles/s41467-017-01358-x
In absence of duplication, the method is not applicable hence no result is returned (NA).
I hope it is clearer now.
Best,
Eric
