### ISSUE TITLE
Using a different signatures file as input

### ISSUE THREAD

**Issue by marcjwilliams1** [FunGeST/Palimpsest#19]
Hi, thanks for the great package.

I'm just wondering what the format of the input signatures file should be. It's currently not obvious to me how the trinucleotide context and the base change are encoded in the column names (eg what CA_A.A etc means). I'd like to use the newest cosmic signatures and wondering how I should format the files from the cosmic site.

Thanks! 
Marc

**Comment by FunGeST** [comment]
Hi Marc,

Thank you for your email.

Regarding the encoding of mutation categories, the first two letters give you the REF and ALT, and the letters after « _ » give you the trinucleotide context, « . » being the mutated base.
So CA_A.A means a C>A mutation in ACA context.

Please find attached the signature file for the new COSMIC signatures.
By the way, we will release this month the v2 of Palimpsest including the new COSMIC signatures and allowing to extract also indel and doublet base substitution signatures!

Best,
Eric

**Comment by marcjwilliams1** [comment]
Thanks for the quick reply. Doesn't look like the file is attached? Anyway I managed to format the file correctly. Thanks
