### ISSUE TITLE
cnaCCF_annot Issue: ntot

### ISSUE THREAD

**Issue by campbellpratt** [FunGeST/Palimpsest#20]
Hi there, 
I'm trying to carry out some clonality analysis, however when I execute cnaCCF_annot, I receive the following error: 
Command: sa.vcf<- cnaCCF_annot(sa.vcf, annot_data=annot_data.sa, cna_data=cna_data.sa, CCF_boundary=0.95)

Error: Error in `[.data.frame`(dfSegm.[[chr]], ind, colsToAdd) : 
  undefined columns selected

The columns within my annotation and copy-number data frames match the corresponding required headers, however I do not have an "ntot" column within my copy-number data. I think this may be the root of the issue, though I noticed that you replied to another issue mentioning  modification of the package to calculate ntot directly from nMin and Maj. I checked code by typing cnaCCF_annot and couldn't see anything adding ntot to the vcf file.

So, a) has this not been updated, and my error is due to missing "ntot" 
or b) is my error due to another issue

Any help is appreciated.
Regards, 
Campbell

**Comment by campbellpratt** [comment]
I added an ntot column to my copy-number data and it runs fine. 
Although I'm getting an issue now when running. It seems that my data for ntot, Nmin, Nmaj, mult, CCF, ccf.adj is not being added to the vcf. Instead, the values are N/A.

**Comment by FunGeST** [comment]
Hi Campbell,

This is quite strange.
Would you be willing to share your input files or a sample of them so we can try on our side and see what goes wrong?

Thanks,
Eric

**Comment by campbellpratt** [comment]
I've attached the files. It's probably been a daft error on my part..
[palimpsest.data.zip](https://github.com/FunGeST/Palimpsest/files/3411398/palimpsest.data.zip)

**Comment by jayendrashinde91** [comment]
@campbellpratt Thanks for the files. Although the method by which you have saved these files is incorrect, I was able to read them as .csv and move forward with the troubleshooting. 

A kind reminder that classes of columns in the input data frame used should reflect the same class used in the example data. You could check by using the following example:
```
>sapply(cna_data,class)

Sample       CHROM   POS_START     POS_END        LogR        ntot 
"character" "character"   "numeric"   "numeric"   "numeric"   "numeric" 
       Nmin        Nmaj      Ploidy 
  "numeric"   "numeric"   "numeric" 
```

The code ran perfectly fine at my end. NAs are strictly generated for SNVs which do not have associated CNA information. 
The following command will give you the idea: 
`>table(vcf$Clonality,useNA="always")`

Hopefully, this should solve your doubt and help you with your analysis.
Best wishes

**Comment by campbellpratt** [comment]
Thanks a lot, after transferring files into the current R terminal I realise that the class of columns did in fact change. All of the data I'm using has successfully run until timing chromosomal gains. Whilst running the command I receive the following error: 

Command: chrom_dup_time <- chrTime_annot (vcf, cna_data = cna_data.gk, cyto=cyto)

Error in '[.data.frame'vcf.,c("Arm", "dup.lev.")) : 
undefined columns selected 

The columns in data and class are all appropriate. Apologies for the hassle.

Campbell

**Comment by campbellpratt** [comment]
Quick update, I ran through the workflow with example data and also failed at this point . I'm unsure what I'm doing wrong so any indication would again be a massively appreciated. 

Campbell

**Comment by beginner984** [comment]
Sorry

I don't have any logR information for copy number data

Can I still use your software for clonality analysis?
Can I put arbitrary 1 for logR?

```
> head(cna_data)
  CHROM POS_START  POS_END            Sample Nmaj Nmin ntot   Ploidy
1  chr1     16298 12889922 LP6005334-DNA_H01    2    1    3 2.487561
2  chr1     16298 12889922 LP6005334-DNA_H01    2    1    3 2.487561
3  chr1     16298 12889922 LP6005334-DNA_H01    2    1    3 2.487561
4  chr1     16298 12889922 LP6005334-DNA_H01    2    1    3 2.487561
5  chr1     16298 12889922 LP6005334-DNA_H01    2    1    3 2.487561
6  chr1     16298 12889922 LP6005334-DNA_H01    2    1    3 2.487561
> 
```

**Comment by beginner984** [comment]
Sorry

Is `ntot` equal to `Nmin + Nmaj` or that is something else?

From your sample input `ntot` does not seem to be `Nmin + Nmaj` so is that segment mean ?

Please help me to get what is `ntot`

Thank you so much

**Comment by FunGeST** [comment]
Hi,

ntot is usually equal to Min + Nmaj.
However, it can slightly differ in cgpBattenberg output, notably when a subclonal CNA is present. In this case we can have an ntot of 2.15 instead of 2 for example.
This will not have a major impact on CCF calculation. If you only have Nmin and Nmaj in your data set you can safely compute ntot as Nmin + Nmaj.

Best,
Eric
