### ISSUE TITLE
Insertion for SV signature

### ISSUE THREAD

**Issue by xtmgah** [FunGeST/Palimpsest#23]
Hello: 

Do you know why insertion were not included in the SV signature analysis? There are only four type SVs including Deletion, Insertion, Dup, inter-chromosomal translocation. Any reason to exclude the Insertion? Also, did intra-chromosomal translocation should included as "Inversion"? Thanks.

**Comment by FunGeST** [comment]
Hi,

Insertions may actually correspond to diverse type of events, e.g. viral insertions, small DNA sequences inserted by repair mechanisms, or complex SVs not fitting within the 4 other categories. That is why we did not include these events which are poorly defined in our signature framework.
For your second question, indeed any intra-chromosomal event will fit within the "deletion", "duplication" or "inversion" category.

Best,
Eric
