### ISSUE TITLE
example data not available when installing using install_github

### ISSUE THREAD

**Issue by ahwanpandey** [FunGeST/Palimpsest#25]
Hello,

It looks like the example data from the vignette as well as some of the resources like the cytoband is not installed by default when using install_github. Is this intended?

Specifically, the following is not downloaded and installed when using `devtools::install_github("FunGeST/Palimpsest")`

Thanks!

![image](https://user-images.githubusercontent.com/8450532/67168222-c1754e80-f3ed-11e9-947f-01d2ecd0a1ff.png)

![image](https://user-images.githubusercontent.com/8450532/67168237-f08bc000-f3ed-11e9-80fd-2afc926f86d9.png)

**Comment by jayendrashinde91** [comment]
Hi,
The example data (LiC1162) from the vignette are not loaded by default.
All other necessary resources for default analysis are loaded automatically on loading the library.
[data.R]("https://github.com/FunGeST/Palimpsest/blob/master/R/data.R)

Also, as explained in the README check out the RUNNING_PALIMPSEST_EXAMPLE folder that contains example data and an R script for a typical Palimpsest analysis.

Best wishes.

**Comment by ahwanpandey** [comment]
Thanks @jayendrashinde91
