### ISSUE TITLE
Trouble with function

### ISSUE THREAD

**Issue by shiguangyini** [FunGeST/Palimpsest#28]
Hi,

I'm new to Palimpsest and 3 days ago I'm successfully to run the Test_Script, Today I'm trying to preprocess and annotate input data according to the updated Test_Script, but I have an error that **could not find all functions**. I tried with other data and it also didn't work thought I removed the old package and install it again. Any suggestion ?

Command: vcf <- annotate_VCF(vcf = vcf, ref_genome = BSgenome.Hsapiens.UCSC.hg19, ref_fasta = "/Genomes/Homo_sapiens_assembly19.fasta",add_ID_cats = FALSE)

Error in annotate_VCF(vcf = vcf, ref_genome = BSgenome.Hsapiens.UCSC.hg19,  : 
  could not find function "annotate_VCF"

**Comment by FunGeST** [comment]
Hi,

Thank you for your message.
We indeed updated Palimpsest 2 days ago to add new functionalities (like indel and double base substitution signatures), and some of the functions have changed.
The annotate_VCF is new to the latest version so I think you should try again removing the old one and reinstalling Palimpsest from Github.
I just tried on my side and it does find the annotate_VCF function.

Keep us posted!
Thanks,
Eric
