### ISSUE TITLE
error when preprocessInput_snv

### ISSUE THREAD

**Issue by zorrodong** [FunGeST/Palimpsest#3]
Hi,

Thanks for the powerful tool. I am using the example data to try Palimpsest, however, I got a error as described below:

> vcf <- preprocessInput_snv(input_data = mut_data,ensgene=ensgene,reference_genome = ref_genome)
[1] "Annotating mutation data:"
  |======================================================================================================| 100%
[1] "Adding mutation categories:"
Error in validObject(result) : 
  invalid class “VRanges” object: 'strand' should be a 'factor' Rle with levels c("+", "-", "*")
> 

Any suggestion?

Looking forward to your reply. Thanks very much!

Best,

Zorro
20180623

**Comment by jayendrashinde91** [comment]
Hi,
Thank you for your interest in Palimpsest.
We are aware of current issue with this particular function.
It occurs with the latest version of R due to certain base function conflicts.
I highly recommend you running Palimpsest with the **R version 3.3.2** on which it was developed.
In the meantime, we are working on a solution to fix this issue and update the package soon.

**Comment by zorrodong** [comment]
Thank very much!

Now I have run successfully with the example data. However, I still have a question, in the cna part, I need  to provide:

LogR: LogR information.
Nmin: Minor allele copy number.
Nmaj: Major allele copy number.

I used Varscan2 and sequenza to calculate the CNA information, I don't know which values correspond to the three values , can you help me to determine them, see below:
![sequenza](https://user-images.githubusercontent.com/13732640/41894246-e19a67ae-7950-11e8-9ff7-db18738d582c.png)

Thank you very much!

Zorro
20180626

**Comment by zorrodong** [comment]
Thanks for the prompt reply, It is really helpful. Sorry to disturb you again, and I go through your Nature communications paper, 2017, and have a question here, see below:
![nc](https://user-images.githubusercontent.com/13732640/41895884-b7348f4e-7955-11e8-8455-c77e333afb2d.png)

Since Palimpsest can only infer tumor evolution in each tumor, how to handle different tumors sampled from the same patient, like the figure above ? Sorry for the naive question, but It really want to know how to process multiple tumors within one patient using Palimpsest.

Looking forward to your reply!

Thanks in advance!

**Comment by FunGeST** [comment]
Unfortunately Palimpsest doesn't allow processing several tumors yet.
For the paper we did it "manually", which is not so complicated from Palimpsest output. Indeed, Palimpsest gives you the natural history of each sample, so you get the number of subclonal mutations (last branch). Then you need to check the overlap between the clonal mutations from each sample to distinguish trunk from intermediate mutations.
However you still need to draw the tree by hand.
We are working on the automatisation of multi-sample analysis but it will only be available in Palimpsest 2 !

**Comment by zorrodong** [comment]
Wow, great, looking forward to Palimpsest 2 ! Thank you very much, It is really a great tool, I will definitely cite it in my paper!

Thanks very much for your patience and nice reply!

Best,

Zorro
20180626
