### ISSUE TITLE
Confusion

### ISSUE THREAD

**Issue by shiguangyini** [FunGeST/Palimpsest#30]
Hi，

I‘m confused there are a total of 60 signatures in SBS_cosmic file, while only 30 signatures in cosmic database and there is no a/b subtype. What is the connection between the 60 signatures and the 30 signatures of cosmic ? Moreover, are parameters about depth required, or  optional ? Hope you can clear up the confusion for me.

Thanks

**Comment by FunGeST** [comment]
Hi,

Thank you for getting in touch.
The new update of Palimpsest uses the latest version of the COSMIC reference signatures, which has been extended to 60 SBS signatures (available here: https://cancer.sanger.ac.uk/cosmic/signatures). 

If you still want to work with the old 30 references, they can be downloaded here: https://cancer.sanger.ac.uk/cancergenome/assets/signatures_probabilities.txt 

If by depth you mean sequencing depth (i.e. `Tumor_Depth` and `Normal_Depth` columns), these are only required for the clonality analysis (section 7 onwards in the Palimsest_Test_Script.R), so you can perform signature extractions of all types without this information. 

I hope this helps! Please let us know if you have any more problems and we'll do our best to help you with them.
Benedict

**Comment by beginner984** [comment]
Sorry, by `Tumor_Depth`, do you mean `ref count + var count ` ?

Thanks a lot

**Comment by FunGeST** [comment]
Yes exactly.
