### ISSUE TITLE
Error in "palimpsest_plotTumorHistories" 

### ISSUE THREAD

**Issue by laloverdin** [FunGeST/Palimpsest#31]
Hi again, 

First thanks for the package, it works pretty well. I got I problem using the function:

palimpsest_plotTumorHistories(vcf` = vcf_chrom,   cna_data = maf_PCNSL_noFlags_palimpsest_v2_2, point.mut.time = point.mut.time, clonsig = signatures_exp_clonal$sig_props, subsig = signatures_exp_subclonal$sig_props, msigcol = `PCNSL_signature_names)

Error in `[.data.frame`(cna_data, ind, c("startarm", "endarm")) : 
  undefined columns selected

I made the following change to the code and it worked perfectly then:

dels <- unique(as.character(as.matrix(cna_data[ind, c("POS_START", 
            "POS_END")])))

Before it was as: 

dels <- unique(as.character(as.matrix(cna_data[ind, c("startarm", 
            "endarm")])))

But... "cna_data" columns are defined as c("POS_START", "POS_END" )   ...hence causing the error

Thought it would be helpful to point out

:)

**Comment by FunGeST** [comment]
Thanks a lot!
We will have a look and correct this.
Eric
