### ISSUE TITLE
Figure 6A&B

### ISSUE THREAD

**Issue by rahulk87** [FunGeST/Palimpsest#37]
Hi, Is there a command to generate figure 6 of manual (there is no command given)?

Thanks!!
[Presentation1.pdf](https://github.com/FunGeST/Palimpsest/files/4329957/Presentation1.pdf)

**Comment by FunGeST** [comment]
Hi Rahul,

Thanks for getting in touch. 

In section 6 of the [Palimpsest Test Script](https://github.com/FunGeST/Palimpsest/blob/master/RUNNING_PALIMPSEST_EXAMPLE/Palimpsest_Test_Script.R) you will find the code that generates these two plots. I hope this is what you're looking for, please let us know if you need help with anything else!

Best wishes,
Benedict

**Comment by rahulk87** [comment]
Thanks Benedict!!
