### ISSUE TITLE
What is "ntot"

### ISSUE THREAD

**Issue by zorrodong** [FunGeST/Palimpsest#4]
Hi,

In your CNA input description, you did not mention "ntot", however, it is necessary for Palimpsest.

I wonder what is "ntot" ? can you help me?

Best,

Zorro
20180629

**Comment by FunGeST** [comment]
Hi,

ntot corresponds to the total copy-number of each segment.
In your sequenza output it should correspond to the CNt column.
We will modify the documentation or update the package to calculate ntot directly from nMin and Maj.

Best,
Eric

**Comment by zorrodong** [comment]
Thank you very much!
