### ISSUE TITLE
Problem in running clonality 

### ISSUE THREAD

**Issue by beginner984** [FunGeST/Palimpsest#47]
Good morning 

I am trying your software on clonality part but I am getting this error 

```
> vcf_cna <- cnaCCF_annot(vcf = vcf, annot_data = d,cna_data = a, CCF_boundary = 0.95)

[1] "LP6005334_DNA_H01"

Error in txtProgressBar(min = 0, max = total, style = 3) :   must have 'max' > 'min'
```

I can share whole R object if needed

Thank you for any help

**Comment by immuneAI** [comment]
Did anyone solve this issue? what's the solution?

**Comment by beginner984** [comment]
No 🙁     On Wednesday, May 22, 2024 at 04:59:25 PM GMT+1, Venkat Addala ***@***.***> wrote:  
 
 


Did anyone solve this issue? what's the solution?
