### ISSUE TITLE
SV data preparing

### ISSUE THREAD

**Issue by xtmgah** [FunGeST/Palimpsest#5]
Hello:

Very good R package to perform the tumor clone evolution study. Thanks. I have a question about the SV data. So, I see the SV data need two breakpoint for each row with the following information:
Sample Type CHROM_1    POS_1 CHROM_2     POS_2 Tumor_Varcount Tumor_Depth Normal_Depth Driver

so, how to calculate the tumor_Depth and Normal_Depth for two location (2 breakpoints)? how to get these two values? Average depth of two breakpoints?

**Comment by FunGeST** [comment]
Hi,
Thanks for reaching out. We are glad that the tool is useful for your research.
Usually, a typical SV vcf file will have PR and SR tags, which mean “Spanning paired-read support for the ref and alt alleles in the order listed” and “Split reads for the ref and alt alleles in the order listed, for reads where P(allele|read)>0.999”.  In our analysis, for a single structural variant, with two breakpoint, we considered the sum of these values:
“Tumor_PR.REF" + "Tumor_SR.REF"+"Tumor_PR.ALT"+"Tumor_SR.ALT” = to define the tumor depth and similarly for the corresponding normal.

**Comment by jayendrashinde91** [comment]
Hi,
Thanks for reaching out. We are glad that the tool is useful for your research.
Usually, a typical SV vcf file will have PR and SR tags, which mean “Spanning paired-read support for the ref and alt alleles in the order listed” and “Split reads for the ref and alt alleles in the order listed, for reads where P(allele|read)>0.999”.  In our analysis, for a single structural variant, with two breakpoint, we considered the sum of these values:
“Tumor_PR.REF" + "Tumor_SR.REF"+"Tumor_PR.ALT"+"Tumor_SR.ALT” = to define the tumor depth and similarly for the corresponding normal.

**Comment by xtmgah** [comment]
Thanks for your information. It's very useful information to us. Which SV calling algorithm you use to generated these vcf file?

**Comment by FunGeST** [comment]
Hi,
We use MANTA to detect somatic SVs (https://github.com/Illumina/manta).
It works nicely and provides the number of read pairs supporting the reference or variant alleles, that we use to calculate the variant allele fraction.
I don't know exactly how the REF counts are estimated given that indeed you must consider two breakpoint positions.
You could probably find the answer in MANTA documentation.
Hope this helps!
Eric

**Comment by xtmgah** [comment]
Thanks for your information.

**Comment by beginner984** [comment]
Sorry, how I can provide information for Tumor_Varcount column?

Thank you for any help
